name: we_fast
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.18.beta <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  flutter_share_me: ^1.2.0
  flutter_svg: ^1.0.1
  get: ^4.6.1
  get_storage: ^2.0.3
  google_maps_flutter: ^2.1.3
  image_cropper: ^1.5.1
  image_picker: ^0.8.4+11
  lottie: ^1.2.1
  razorpay_flutter: ^1.3.0
  sizer: ^2.0.15
  contacts_service: ^0.6.3
  
  permission_handler: ^10.0.0
  fluttercontactpicker: ^4.7.0

dev_dependencies:
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Cabin
      fonts:
        - asset: assets/font/Cabin/Cabin-Bold.ttf
          weight: 700
        - asset: assets/font/Cabin/Cabin-Italic.ttf
          style: italic
        - asset: assets/font/Cabin/Cabin-Medium.ttf
          weight: 500
        - asset: assets/font/Cabin/Cabin-Regular.ttf
          weight: 400
        - asset: assets/font/Cabin/Cabin-SemiBold.ttf
          weight: 600
    - family: NavBarIcons
      fonts:
        - asset: assets/font/NavBarIcons.ttf
